# Previsão do mercado financeiro

## Módulo 1 - Base de Dados

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import pytz

Download dos dados por meio da biblioteca *yfinance*:

In [2]:
petr = yf.download(tickers="PETR4.SA", start = "2020-05-01", end = "2022-03-31", interval = "60m")
oil = yf.download(tickers="CL=F", start = "2020-05-01", end = "2022-03-31", interval = "60m")
dollar = yf.download(tickers="BRL=X", start = "2020-05-01", end = "2022-03-31", interval = "60m")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [3]:
oil.loc[oil.index > "2020-05-24"].head(50) # dia 25/05/2020 está faltando, assim como vários outros.

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2020-05-24 19:00:00-04:00,33.060001,33.090000,32.790001,32.889999,32.889999,2458
2020-05-24 20:00:00-04:00,32.889999,33.259998,32.889999,33.070000,33.070000,4192
2020-05-24 21:00:00-04:00,33.090000,33.150002,32.860001,32.950001,32.950001,4282
2020-05-26 00:00:00-04:00,34.180000,34.439999,34.180000,34.360001,34.360001,4735
2020-05-26 01:00:00-04:00,34.360001,34.430000,34.299999,34.369999,34.369999,4125
2020-05-26 02:00:00-04:00,34.360001,34.540001,34.299999,34.470001,34.470001,7941
2020-05-26 03:00:00-04:00,34.480000,34.509998,34.369999,34.389999,34.389999,6349
2020-05-26 04:00:00-04:00,34.400002,34.400002,33.759998,33.950001,33.950001,17007
2020-05-26 05:00:00-04:00,33.959999,34.220001,33.910000,34.080002,34.080002,9699
2020-05-26 06:00:00-04:00,34.080002,34.150002,33.939999,34.119999,34.119999,7937
2020-05-26 07:00:00-04:00,34.119999,34.180000,33.990002,34.049999,34.049999,6283
2020-05-26 08:00:00-04:00,34.060001,34.450001,33.950001,34.410000,34.410000,19636
2020-05-26 09:00:00-04:00,34.410000,34.810001,34.169998,34.200001,34.200001,48882
2020-05-26 10:00:00-04:00,34.200001,34.320000,33.810001,34.040001,34.040001,42267
2020-05-26 11:00:00-04:00,34.049999,34.060001,33.470001,33.490002,33.490002,38352
2020-05-26 12:00:00-04:00,33.490002,33.919998,33.380001,33.910000,33.910000,26252
2020-05-26 13:00:00-04:00,33.910000,34.230000,33.799999,33.849998,33.849998,26254
2020-05-26 14:00:00-04:00,33.840000,34.500000,33.779999,34.099998,34.099998,45724
2020-05-26 15:00:00-04:00,34.099998,34.240002,33.919998,34.130001,34.130001,9288
2020-05-26 16:00:00-04:00,34.130001,34.380001,34.090000,34.169998,34.169998,4681
2020-05-26 18:00:00-04:00,34.139999,34.220001,34.029999,34.060001,34.060001,0
2020-05-26 19:00:00-04:00,34.070000,34.070000,33.740002,34.049999,34.049999,3555
2020-05-26 20:00:00-04:00,34.060001,34.139999,33.759998,33.990002,33.990002,3984
2020-05-26 21:00:00-04:00,33.980000,34.160000,33.930000,33.980000,33.980000,4689
2020-05-26 22:00:00-04:00,33.980000,34.080002,33.840000,34.070000,34.070000,4117
2020-05-26 23:00:00-04:00,34.070000,34.320000,34.060001,34.220001,34.220001,5247
2020-05-27 00:00:00-04:00,34.200001,34.279999,34.139999,34.230000,34.230000,2456
2020-05-27 01:00:00-04:00,34.230000,34.230000,34.009998,34.029999,34.029999,3675
2020-05-27 02:00:00-04:00,34.040001,34.189999,33.650002,33.730000,33.730000,10768
2020-05-27 03:00:00-04:00,33.730000,33.860001,33.529999,33.660000,33.660000,12600
2020-05-27 04:00:00-04:00,33.669998,34.119999,33.509998,34.080002,34.080002,13682
2020-05-27 05:00:00-04:00,34.080002,34.230000,33.970001,34.200001,34.200001,8823
2020-05-27 06:00:00-04:00,34.200001,34.270000,33.849998,33.939999,33.939999,8897
2020-05-27 07:00:00-04:00,33.950001,34.040001,33.709999,33.790001,33.790001,9550
2020-05-27 08:00:00-04:00,33.799999,33.959999,33.360001,33.389999,33.389999,19612
2020-05-27 09:00:00-04:00,33.400002,33.740002,33.180000,33.230000,33.230000,47942
2020-05-27 10:00:00-04:00,33.189999,33.450001,32.180000,32.360001,32.360001,76153
2020-05-27 11:00:00-04:00,32.369999,33.240002,32.279999,33.119999,33.119999,56049
2020-05-27 12:00:00-04:00,33.119999,33.570000,33.080002,33.290001,33.290001,31863
2020-05-27 13:00:00-04:00,33.290001,33.419998,32.860001,32.930000,32.930000,23621
2020-05-27 14:00:00-04:00,32.930000,33.090000,32.430000,32.599998,32.599998,31767
2020-05-27 15:00:00-04:00,32.610001,32.980000,32.509998,32.860001,32.860001,7926
2020-05-27 16:00:00-04:00,32.860001,32.900002,31.750000,32.220001,32.220001,12897
2020-05-27 18:00:00-04:00,32.099998,32.389999,31.570000,31.639999,31.639999,0
2020-05-27 19:00:00-04:00,31.650000,31.780001,31.139999,31.750000,31.750000,8208
2020-05-27 20:00:00-04:00,31.740000,32.080002,31.709999,31.870001,31.870001,7301
2020-05-27 21:00:00-04:00,31.879999,32.169998,31.740000,32.049999,32.049999,8514
2020-05-27 22:00:00-04:00,32.049999,32.080002,31.600000,31.760000,31.760000,7240
2020-05-27 23:00:00-04:00,31.750000,31.760000,31.299999,31.389999,31.389999,8634
2020-05-28 00:00:00-04:00,31.350000,31.680000,31.299999,31.600000,31.600000,5317

Renomeação das features de interesse em cada base:

In [4]:
dollar.rename(columns={'Close':'dollar'}, inplace=True)
oil.rename(columns={'Close':'oil'}, inplace=True)

Unindo os dados com left_join:

In [5]:
data01 = pd.merge(petr, oil["oil"], how = "left", left_index=True, right_index=True)

In [6]:
data02 = pd.merge(data01, dollar["dollar"], how = "left", left_index=True, right_index=True)

In [7]:
data03 = data02.tz_convert('Brazil/East')

In [8]:
data03.head()

,Open,High,Low,Close,Adj Close,Volume,oil,dollar
Datetime,,,,,,,,
2020-05-04 10:00:00-03:00,17.430000,17.620001,17.350000,17.520000,17.520000,0.0,19.840000,5.5746
2020-05-04 11:00:00-03:00,17.520000,17.590000,17.410000,17.420000,17.420000,8867100.0,19.809999,5.5906
2020-05-04 12:00:00-03:00,17.420000,17.469999,17.230000,17.240000,17.240000,9610700.0,19.870001,5.5712
2020-05-04 13:00:00-03:00,17.240000,17.330000,17.230000,17.299999,17.299999,5103400.0,20.200001,5.5680
2020-05-04 14:00:00-03:00,17.299999,17.309999,17.200001,17.250000,17.250000,4075100.0,20.219999,5.5626

In [9]:
data03.isna().sum()

Open          1
High          1
Low           1
Close         1
Adj Close     1
Volume        1
oil          87
dollar        3
dtype: int64

In [68]:
from pytrends.request import TrendReq

pytrends = TrendReq(hl='en-US', tz=180)
kw_list = ['PETR4','PETROBRAS',"CRISE"]

google_tr = pytrends.get_historical_interest(kw_list, year_start=2020,
                                             month_start=5, day_start=1,
                                             hour_start=0, year_end=2022,
                                             month_end=3, day_end=31, hour_end=0,
                                             cat=0, geo='', gprop='', sleep=60)

In [69]:
google_tr.head()

                     PETR4  PETROBRAS  CRISE  isPartial
date
2020-05-01 00:00:00     10         28     68      False
2020-05-01 01:00:00      8         21     70      False
2020-05-01 02:00:00     13         20     55      False
2020-05-01 03:00:00      6         17     48      False
2020-05-01 04:00:00      0          3     29      False

In [70]:
google_tr = google_tr.tz_localize(tz='Brazil/East')

In [72]:
google_tr.head(85)

                           PETR4  PETROBRAS  CRISE  isPartial
date
2020-05-01 00:00:00-03:00     10         28     68      False
2020-05-01 01:00:00-03:00      8         21     70      False
2020-05-01 02:00:00-03:00     13         20     55      False
2020-05-01 03:00:00-03:00      6         17     48      False
2020-05-01 04:00:00-03:00      0          3     29      False
...                          ...        ...    ...        ...
2020-05-04 08:00:00-03:00      1          4     44      False
2020-05-04 09:00:00-03:00      0          3     64      False
2020-05-04 10:00:00-03:00      3          7     76      False
2020-05-04 11:00:00-03:00      2          5     80      False
2020-05-04 12:00:00-03:00      5         13     57      False

[85 rows x 4 columns]

In [136]:
data04 = pd.merge(data03, google_tr, how = "left", left_index=True, right_index=True)

In [137]:
data04.head()

,Open,High,Low,Close,Adj Close,Volume,oil,dollar,PETR4,PETROBRAS,CRISE,isPartial
2020-05-04 10:00:00-03:00,17.430000,17.620001,17.350000,17.520000,17.520000,0.0,19.840000,5.5746,3.0,7.0,76.0,False
2020-05-04 11:00:00-03:00,17.520000,17.590000,17.410000,17.420000,17.420000,8867100.0,19.809999,5.5906,2.0,5.0,80.0,False
2020-05-04 12:00:00-03:00,17.420000,17.469999,17.230000,17.240000,17.240000,9610700.0,19.870001,5.5712,5.0,13.0,57.0,False
2020-05-04 13:00:00-03:00,17.240000,17.330000,17.230000,17.299999,17.299999,5103400.0,20.200001,5.5680,21.0,21.0,89.0,False
2020-05-04 14:00:00-03:00,17.299999,17.309999,17.200001,17.250000,17.250000,4075100.0,20.219999,5.5626,34.0,37.0,63.0,False

In [138]:
data04.isna().sum()

Open          1
High          1
Low           1
Close         1
Adj Close     1
Volume        1
oil          87
dollar        3
PETR4         3
PETROBRAS     3
CRISE         3
isPartial     3
dtype: int64

In [139]:
data04.to_csv("puc_full_3.csv", date_format = '%Y-%m-%d %H:%M:%S')