## Preparando os dados para treinar os modelos - Per√≠odo de 2 anos

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import asarray
from numpy import savetxt

### Carregando os dados

In [23]:
data = pd.read_csv("data/trabalho_final4.csv", parse_dates=True)
data.index = data["date"]
data.index = pd.to_datetime(data.index)
data.index.name = "date"
data.drop(["date"], inplace = True, axis = 1)

In [24]:
data.head()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class
date,,,,,,,,,,,,,,
2020-08-10 10:00:00,-0.006745,51.0,0.0,0.013484,0.0,8.0,0.001842,0.207372,-0.166388,0,0,0,-0.000878,0.0
2020-08-10 11:00:00,0.004875,62.0,4043200.0,-0.004989,2.0,20.0,0.001674,0.187121,-0.149311,0,0,0,-0.004392,0.0
2020-08-10 12:00:00,0.004240,90.0,3890900.0,0.005253,4.0,7.0,0.001617,0.161146,-0.140229,1,0,0,0.003970,1.0
2020-08-10 13:00:00,-0.001088,58.0,1918000.0,0.003563,33.0,27.0,-0.000671,0.146137,-0.124190,0,0,0,0.015817,1.0
2020-08-10 14:00:00,0.007567,58.0,10996700.0,-0.002367,30.0,29.0,-0.000145,0.161432,-0.087117,0,0,1,0.006920,1.0

In [25]:
data.isna().sum()

dollar          0
CRISE           0
r_vol           0
r_oil           0
r_PETR4         0
r_PETROBRAS     0
ma24            0
macd            0
macdhist        0
bbands          0
rsi_dummy       0
atr_dummy       0
target_value    0
target_class    0
dtype: int64

In [26]:
data.describe()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class
count,2926.000000,2926.000000,2.926000e+03,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000,2926.000000
mean,-0.000027,52.477444,7.719676e+06,0.000421,13.507861,20.831795,0.000098,0.018761,-0.000419,0.201640,0.118592,0.156869,0.000170,0.485988
std,0.004316,15.410486,5.219333e+06,0.010813,11.760710,11.372552,0.001985,0.295425,0.099392,0.401294,0.323363,0.363740,0.011563,0.499889
min,-0.037218,2.000000,0.000000e+00,-0.097174,0.000000,0.000000,-0.011135,-1.802307,-0.830058,0.000000,0.000000,0.000000,-0.207478,0.000000
25%,-0.001974,45.000000,4.380150e+06,-0.003413,3.000000,13.000000,-0.000949,-0.151760,-0.051544,0.000000,0.000000,0.000000,-0.003643,0.000000
50%,0.000019,54.000000,6.750600e+06,0.000198,12.000000,19.000000,0.000189,0.039242,-0.000131,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.001920,62.000000,1.022460e+07,0.004034,21.000000,27.000000,0.001305,0.202823,0.056452,0.000000,0.000000,0.000000,0.003990,1.000000
max,0.024329,100.000000,2.850740e+07,0.182640,76.000000,71.000000,0.006641,0.844836,0.366460,1.000000,1.000000,1.000000,0.160256,1.000000

### Separando set de treino e set de teste

In [27]:
TrainLen = int(len(data) * 0.80)
TestLen = len(data) - TrainLen
print("Tamanho do set de treino:", TrainLen, "\nTamanho do set de teste:", TestLen)

Tamanho do set de treino: 2340
Tamanho do set de teste: 586

In [28]:
TrainData = data.iloc[0:TrainLen,:] 
TestData  = data.iloc[TrainLen:len(data),:]
print("Formato do set de treino:", TrainData.shape,"\nFormato do set de treino:", TestData.shape)

Formato do set de treino: (2340, 14)
Formato do set de treino: (586, 14)

In [29]:
TrainData.tail()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class
date,,,,,,,,,,,,,,
2022-02-01 11:00:00,-0.001645,37.0,8180400.0,0.003439,6.0,23.0,-0.001667,-0.183144,-0.177566,0,0,1,0.021485,1.0
2022-02-01 12:00:00,0.000265,70.0,13830500.0,0.007996,15.0,19.0,-0.000835,-0.126269,-0.096553,0,0,1,-0.006911,0.0
2022-02-01 13:00:00,0.000019,53.0,4610600.0,-0.003400,19.0,31.0,-0.001397,-0.098617,-0.055121,0,0,0,-0.003026,0.0
2022-02-01 14:00:00,0.000852,45.0,2652400.0,0.001137,15.0,20.0,-0.001461,-0.083806,-0.032248,0,0,0,0.000910,1.0
2022-02-01 15:00:00,-0.002441,58.0,4220500.0,-0.001477,16.0,38.0,-0.001201,-0.068853,-0.013836,0,0,0,-0.003942,0.0

In [30]:
TestData.head()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class
date,,,,,,,,,,,,,,
2022-02-02 10:00:00,0.004078,55.0,7729100.0,0.016949,4.0,4.0,-0.002104,-0.066724,-0.009366,0,0,0,-0.010046,0.0
2022-02-02 11:00:00,0.002569,38.0,6692300.0,-0.018121,2.0,21.0,-0.002121,-0.090620,-0.026610,0,0,0,0.006150,1.0
2022-02-02 12:00:00,-0.001545,57.0,3264100.0,0.002620,0.0,29.0,-0.002113,-0.092355,-0.022676,0,0,0,-0.005196,0.0
2022-02-02 13:00:00,0.001170,80.0,2591800.0,-0.002727,17.0,24.0,-0.002130,-0.106223,-0.029235,0,0,0,-0.001536,0.0
2022-02-02 14:00:00,-0.002017,48.0,2784400.0,-0.001139,26.0,22.0,-0.001831,-0.119867,-0.034303,0,0,0,-0.000615,0.0

In [31]:
TrainData.columns

Index(['dollar', 'CRISE', 'r_vol', 'r_oil', 'r_PETR4', 'r_PETROBRAS', 'ma24',
       'macd', 'macdhist', 'bbands', 'rsi_dummy', 'atr_dummy', 'target_value',
       'target_class'],
      dtype='object')

### Normaliza√ß√£o

In [32]:
from sklearn.preprocessing import MinMaxScaler

TrainX = TrainData[['dollar', 'CRISE', 'r_vol', 'r_oil', 'r_PETR4', 'r_PETROBRAS', 'ma24','macd', 'macdhist', 'bbands', 'rsi_dummy','atr_dummy']]
TrainY = TrainData[['target_value','target_class']]
                   
TrainScaler = MinMaxScaler()
TrainX_Scaled = TrainScaler.fit_transform(TrainX)

In [33]:
print(TrainY)

                     target_value  target_class
date
2020-08-10 10:00:00     -0.000878           0.0
2020-08-10 11:00:00     -0.004392           0.0
2020-08-10 12:00:00      0.003970           1.0
2020-08-10 13:00:00      0.015817           1.0
2020-08-10 14:00:00      0.006920           1.0
...                           ...           ...
2022-02-01 11:00:00      0.021485           1.0
2022-02-01 12:00:00     -0.006911           0.0
2022-02-01 13:00:00     -0.003026           0.0
2022-02-01 14:00:00      0.000910           1.0
2022-02-01 15:00:00     -0.003942           0.0

[2340 rows x 2 columns]

In [34]:
TrainX_Scaled

array([[0.49511011, 0.51041667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.68390385, 0.625     , 0.14182984, ..., 0.        , 0.        ,
        0.        ],
       [0.67359319, 0.91666667, 0.13648737, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.60501138, 0.53125   , 0.16173344, ..., 0.        , 0.        ,
        0.        ],
       [0.61854917, 0.44791667, 0.09304251, ..., 0.        , 0.        ,
        0.        ],
       [0.56504506, 0.58333333, 0.14804928, ..., 0.        , 0.        ,
        0.        ]])

In [35]:
TrainX.dollar.describe()

count    2340.000000
mean       -0.000002
std         0.004255
min        -0.037218
25%        -0.001866
50%         0.000089
75%         0.001944
max         0.024329
Name: dollar, dtype: float64

In [36]:
TrainX.dollar

date
2020-08-10 10:00:00   -0.006745
2020-08-10 11:00:00    0.004875
2020-08-10 12:00:00    0.004240
2020-08-10 13:00:00   -0.001088
2020-08-10 14:00:00    0.007567
                         ...
2022-02-01 11:00:00   -0.001645
2022-02-01 12:00:00    0.000265
2022-02-01 13:00:00    0.000019
2022-02-01 14:00:00    0.000852
2022-02-01 15:00:00   -0.002441
Name: dollar, Length: 2340, dtype: float64

In [37]:
(-0.006745-(-0.037218))/(0.024329-(-0.037218))

0.495117552439599

In [38]:
from sklearn.preprocessing import MinMaxScaler

TestX = TestData[['dollar', 'CRISE', 'r_vol', 'r_oil', 'r_PETR4', 'r_PETROBRAS', 'ma24','macd', 'macdhist', 'bbands', 'rsi_dummy','atr_dummy']]
TestY = TestData[['target_value','target_class']]
                   

TestScaler = MinMaxScaler()
TestX_Scaled = TestScaler.fit_transform(TestX)

In [39]:
TestX_Scaled.shape

(586, 12)

In [40]:
print(TestY)

                     target_value  target_class
date
2022-02-02 10:00:00     -0.010046           0.0
2022-02-02 11:00:00      0.006150           1.0
2022-02-02 12:00:00     -0.005196           0.0
2022-02-02 13:00:00     -0.001536           0.0
2022-02-02 14:00:00     -0.000615           0.0
...                           ...           ...
2022-06-07 11:00:00     -0.002259           0.0
2022-06-07 12:00:00      0.000970           1.0
2022-06-07 13:00:00     -0.005816           0.0
2022-06-07 14:00:00      0.002275           1.0
2022-06-07 15:00:00     -0.004864           0.0

[586 rows x 2 columns]

In [41]:
print(TrainX_Scaled)

[[0.49511011 0.51041667 0.         ... 0.         0.         0.        ]
 [0.68390385 0.625      0.14182984 ... 0.         0.         0.        ]
 [0.67359319 0.91666667 0.13648737 ... 1.         0.         0.        ]
 ...
 [0.60501138 0.53125    0.16173344 ... 0.         0.         0.        ]
 [0.61854917 0.44791667 0.09304251 ... 0.         0.         0.        ]
 [0.56504506 0.58333333 0.14804928 ... 0.         0.         0.        ]]

In [42]:
savetxt('TrainX_Scaled.csv', TrainX_Scaled, delimiter=',')
savetxt('TestX_Scaled.csv', TestX_Scaled, delimiter=',')

In [43]:
TrainY.to_csv("TrainY.csv", date_format = '%Y-%m-%d %H:%M:%S')
TestY.to_csv("TestY.csv", date_format = '%Y-%m-%d %H:%M:%S')

### Prepara√ß√£o dos Dados - Per√≠odo de 4 meses com an√°lise de sentimento

In [44]:
data_tweets = pd.read_csv("data/trabalho_final_tweets.csv", parse_dates=True)
data_tweets.index = data_tweets["date"]
data_tweets.index = pd.to_datetime(data_tweets.index)
data_tweets.index.name = "date"
data_tweets.drop(["date"], inplace = True, axis = 1)

In [45]:
data_tweets.head()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class,sentimento
date,,,,,,,,,,,,,,,
2022-02-01 10:00:00,-0.002264,79.0,7327800.0,-0.006831,0.0,17.0,-0.002172,-0.181801,-0.220615,0,0,0,0.011487,1.0,0.7964
2022-02-01 12:00:00,0.000265,70.0,13830500.0,0.007996,15.0,19.0,-0.000835,-0.126269,-0.096553,0,0,1,-0.006911,0.0,0.0000
2022-02-01 13:00:00,0.000019,53.0,4610600.0,-0.003400,19.0,31.0,-0.001397,-0.098617,-0.055121,0,0,0,-0.003026,0.0,-0.4767
2022-02-01 14:00:00,0.000852,45.0,2652400.0,0.001137,15.0,20.0,-0.001461,-0.083806,-0.032248,0,0,0,0.000910,1.0,0.2732
2022-02-02 10:00:00,0.004078,55.0,7729100.0,0.016949,4.0,4.0,-0.002104,-0.066724,-0.009366,0,0,0,-0.010046,0.0,0.0000

In [46]:
data_tweets.describe()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class,sentimento
count,567.000000,567.000000,5.670000e+02,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000,567.000000
mean,-0.000135,51.405644,7.487573e+06,0.000594,14.545855,27.795414,-0.000172,-0.034689,0.000687,0.165785,0.100529,0.139330,0.000191,0.516755,0.325190
std,0.004605,12.207764,4.985434e+06,0.016777,11.732238,12.665016,0.001963,0.333268,0.115539,0.372216,0.300970,0.346596,0.014940,0.500160,0.609297
min,-0.016911,20.000000,0.000000e+00,-0.097174,0.000000,2.000000,-0.008958,-0.864748,-0.561407,0.000000,0.000000,0.000000,-0.130795,0.000000,-0.975000
25%,-0.002286,43.000000,4.356950e+06,-0.005135,4.000000,19.000000,-0.001377,-0.278899,-0.066011,0.000000,0.000000,0.000000,-0.003676,0.000000,-0.102700
50%,-0.000175,52.000000,7.019300e+06,0.000262,13.000000,27.000000,0.000123,-0.000592,0.015368,0.000000,0.000000,0.000000,0.000308,1.000000,0.476700
75%,0.001754,59.500000,1.011735e+07,0.005993,22.000000,35.500000,0.001199,0.227176,0.079747,0.000000,0.000000,0.000000,0.004213,1.000000,0.891000
max,0.023624,100.000000,2.686620e+07,0.182640,76.000000,67.000000,0.004681,0.617867,0.220754,1.000000,1.000000,1.000000,0.160256,1.000000,0.998600

### Separando set de treino e set de teste

In [56]:
TrainLen2 = int(len(data_tweets) * 0.85)
TestLen2 = len(data_tweets) - TrainLen2
print("Tamanho do set de treino:", TrainLen2, "\nTamanho do set de teste:", TestLen2)

Tamanho do set de treino: 481
Tamanho do set de teste: 86

In [57]:
TrainData2 = data_tweets.iloc[0:TrainLen2,:] 
TestData2  = data_tweets.iloc[TrainLen2:len(data_tweets),:]
print("Formato do set de treino:", TrainData2.shape,"\nFormato do set de treino:", TestData2.shape)

Formato do set de treino: (481, 15)
Formato do set de treino: (86, 15)

In [58]:
TrainData2.tail()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class,sentimento
date,,,,,,,,,,,,,,,
2022-05-19 16:00:00,0.004986,55.0,9059300.0,-0.008894,29.0,29.0,-0.000622,0.003612,0.020322,0,0,0,0.014603,1.0,0.9953
2022-05-20 10:00:00,-0.007239,36.0,0.0,0.011486,0.0,10.0,-0.000012,0.061085,0.062235,0,0,0,-0.009211,0.0,0.8481
2022-05-20 11:00:00,-0.004240,40.0,9821400.0,-0.001065,9.0,17.0,-0.000440,0.079890,0.064832,0,0,0,0.002324,1.0,-0.0772
2022-05-20 12:00:00,-0.000432,55.0,7506300.0,0.001155,6.0,24.0,-0.000171,0.100094,0.068030,0,0,0,-0.003768,0.0,0.9968
2022-05-20 13:00:00,0.001379,53.0,5455000.0,-0.000798,22.0,30.0,-0.000232,0.104413,0.057879,0,0,0,0.007856,1.0,0.9741

In [59]:
TestData2.head()

,dollar,CRISE,r_vol,r_oil,r_PETR4,r_PETROBRAS,ma24,macd,macdhist,bbands,rsi_dummy,atr_dummy,target_value,target_class,sentimento
date,,,,,,,,,,,,,,,
2022-05-20 14:00:00,0.000432,40.0,9483600.0,0.010565,41.0,20.0,0.000574,0.128145,0.065289,0,0,1,-0.001443,0.0,-0.1779
2022-05-20 15:00:00,-0.000144,51.0,9454000.0,-0.009927,23.0,23.0,0.000391,0.141290,0.062747,0,0,0,0.004626,1.0,0.7096
2022-05-20 16:00:00,0.000411,58.0,12301200.0,-0.009849,18.0,26.0,0.000598,0.162742,0.067359,0,0,1,0.019281,1.0,0.9153
2022-05-23 10:00:00,-0.014683,46.0,0.0,-0.009947,1.0,6.0,0.001355,0.231142,0.108607,0,0,1,0.011293,1.0,-0.9246
2022-05-23 11:00:00,-0.000250,53.0,16295900.0,-0.007603,4.0,18.0,0.001840,0.314006,0.153177,0,0,1,0.001396,1.0,0.2023

### Normaliza√ß√£o

In [62]:
from sklearn.preprocessing import MinMaxScaler

TrainX2 = TrainData2[['dollar', 'CRISE', 'r_vol', 'r_oil', 'r_PETR4', 'r_PETROBRAS', 'ma24','macd', 'macdhist', 'bbands', 'rsi_dummy','atr_dummy', "sentimento"]]
TrainY2 = TrainData2[['target_value','target_class']]
                   
TrainScaler2 = MinMaxScaler()
TrainX_Scaled2 = TrainScaler2.fit_transform(TrainX2)

In [63]:
TrainX_Scaled2.shape

(481, 13)

In [64]:
from sklearn.preprocessing import MinMaxScaler

TestX2 = TestData2[['dollar', 'CRISE', 'r_vol', 'r_oil', 'r_PETR4', 'r_PETROBRAS', 'ma24','macd', 'macdhist', 'bbands', 'rsi_dummy','atr_dummy', "sentimento"]]
TestY2 = TestData2[['target_value','target_class']]
                   

TestScaler2 = MinMaxScaler()
TestX_Scaled2 = TestScaler2.fit_transform(TestX2)

In [65]:
TestX_Scaled2.shape

(86, 13)

In [66]:
savetxt('TrainX_Scaled2.csv', TrainX_Scaled2, delimiter=',')
savetxt('TestX_Scaled2.csv', TestX_Scaled2, delimiter=',')

In [67]:
TrainY2.to_csv("TrainY2.csv", date_format = '%Y-%m-%d %H:%M:%S')
TestY2.to_csv("TestY2.csv", date_format = '%Y-%m-%d %H:%M:%S')